//! Test whether an ONNX model can run one CPU forward pass through Crane's
//! Candle-backed ONNX evaluator.

#[cfg(feature = "onnx")]
fn main() {
    let mut args = std::env::args().skip(1);
    let Some(model_path) = args.next() else {
        print_usage();
        std::process::exit(2);
    };
    if matches!(model_path.as_str(), "-h" | "--help") {
        print_usage();
        return;
    }

    let mut dynamic_dim = 1;
    while let Some(argument) = args.next() {
        match argument.as_str() {
            "--dynamic-dim" => match args.next().and_then(|value| value.parse::<usize>().ok()) {
                Some(value) if value > 0 => dynamic_dim = value,
                _ => {
                    eprintln!("error: --dynamic-dim requires a positive integer");
                    std::process::exit(2);
                },
            },
            "-h" | "--help" => {
                print_usage();
                return;
            },
            _ => {
                eprintln!("error: unknown argument '{argument}'");
                print_usage();
                std::process::exit(2);
            },
        }
    }

    println!("Probing '{}' with Candle through crane_core…", model_path);
    match crane_core::onnx::probe_onnx_model(&model_path, dynamic_dim) {
        Ok(report) => {
            println!("SUCCESS: Candle loaded the model and completed one CPU forward pass.");
            println!("Inputs generated by the probe:");
            for input in report.inputs {
                println!("  {}: {} {:?}", input.name, input.dtype, input.shape);
            }
            println!("Outputs:");
            for output in report.outputs {
                println!("  {}: {} {:?}", output.name, output.dtype, output.shape);
            }
            println!("Evaluated {} graph node(s).", report.operations.len());
        },
        Err(error) => {
            eprintln!("FAILED: {error:#}");
            std::process::exit(1);
        },
    }
}

#[cfg(feature = "onnx")]
fn print_usage() {
    eprintln!(
        "Usage: cargo run -p crane-examples --features onnx --bin onnx_probe -- <model.onnx> [--dynamic-dim N]\n\nThe probe creates zero-filled CPU inputs. Unknown/symbolic ONNX dimensions default to 1; set --dynamic-dim to your expected batch or sequence size."
    );
}

#[cfg(not(feature = "onnx"))]
fn main() {
    eprintln!("onnx_probe requires the ONNX feature.");
    eprintln!("Run: cargo run -p crane-examples --features onnx --bin onnx_probe -- <model.onnx>");
    std::process::exit(2);
}
